addons:
  apt:
    sources:
    - docker-xenial
    packages:
    - docker-ce
    - qemu

env:
  global:
  - VERSION=${TRAVIS_BRANCH}
  - DOCKER_USERNAME=cjyar
  # DOCKER_PASSWORD:
  - secure: "LHtSsr8cd6L0AtMOv6RlzENd+a8f2VdJ7vNjeHeTNkkV6Fm3Rb6UP3naVaQaMCTv0mjqgNNlM/hEcGEIisARD9WcCQojVaJxWW5YDXu9EEMCbDmiXA7BBthSq/sHCypKwUIIunvdiV47uRDkkPuQFCqMPxY+JPlZPtDymzF6MjIFIwW/t7DcfSeRUA/Q8h6Z4hVPbxaAZRvuk6nmFVn89tImi9WCiRit2kC1fS7BIlHz2DQVwEXiAzdk4szVii9UiKzR0/RjHXqEEtNmXf4SiPnHe5ZKu6DPQRF/DDYyYft/lQhFm71pYjhcwY4XcJjs2cbJsaYS2M/zzcP2bfICAZS6FfoFKHU2Mcj9SttOit/5rrj02JAzCPcofUX3umLf5rCDRmD5synrtqnNTQN0efO4S8WyheekjilMxys0djnWC5fnW2nwtNwRzdn82G56t1UfnOuKhMPhDbTnz0ubBTT3YryvDCOGYdlRks3LyKpbnVtZi2lO2Pgp8ji86LFza1MaDFEFnChzr9WOyPxyphO78sPrunOLt9NwiEKz1FqnU0SeAB1zY8q/h5jcOIGVty6MxtQmdSMPJjJeoeuThBVAsgfEVzVN+YdXLve1bVpHMzV3pH3aGLvSSGbK+v6/w5Tt2oTAOfthl5q25L/w51LN/TECDao+jvBdP39rL3o="

services:
- docker

before-script:
# Enable experimental mode so we can use buildx.
- mkdir -p ${HOME}/.docker
- echo '{"experimental":"enabled"}' > ${HOME}/.docker/config.json
# Set up Docker authentication.
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
# This container configures QEMU for Docker buildx.
- docker run --privileged linuxkit/binfmt:v0.7
# Create a new buildx builder to do multi-arch.
- docker buildx create --driver docker-container --name multi --use
# Get the list of platforms to build on.
- "PLATFORMS=$(docker buildx inspect --bootstrap | egrep '^Platforms: ' | sed -e 's,Platforms: ,,' -e 's, ,,g')"
# Convenience so we can use "docker build" instead of "docker buildx build".
- docker buildx install

script:
- docker build -t cjyar/docker-multi-arch:${VERSION} --push --platform ${PLATFORMS} .
