addons:
  apt:
    sources:
    - docker-xenial
    packages:
    - docker-ce
    - qemu

env:
  global:
  - VERSION=${TRAVIS_BRANCH}
  - DOCKER_USERNAME=cjyar
  # DOCKER_PASSWORD:
  - secure: "OcdoiywEO0wPGnMxT5inBdATlK1CfpW/UkBHn2s5xaKyCvz+zDHxxRRprrhH1uqZm0SVj6zdjTsYDseVg9++eqIFR+T5H+M6ifpW3BRkAY1CJeC+WSMA4PAMd7LdOWmRK3m9bEUNuUdlLEmZDoprSWSwvBw5gTodS8ltO8vvtm6atVUlgZ5JqA7jUbDXYr3xJykQAId2paQbUrIQnwAvXtqBv1NP7yVZP23/LzYqcSjuGgSUyV8lteqELqoRLGtLDk/6LQlcjPrnSXtPtRZZwJt4+ZcbfVdRHpPREZ2WaBITuQTS1/GaMX9g3ORj51VhbYgyx4kxJXZmEsFWMiReNopaB1XFx4PhKkpPiIkiz9flNpY5Chc2eRKQhq+ewJLP4SCqzBUP1i0Vu4xrUS8TvvTiHxdUB7tMsw5tXEw8zjzIBitquuXXxo7xEROuCTPKvc/VHHrpbEVGAu8pX0vk6mPeNqGZgW4nP6H09+AItzRavJnKwYy2DO0uPwwCUl0wpceCOanXbybY49enZ5wZqGsqgjE1v8Nj6jG0g/ja8kr/XQESLr2FqApyH5qrFw6gaXjPSfEVQk7XXLnz28TnOUN3sdb0w71snHRD+rF62VxqfYUN12ax/J+t9MsLi4hH35THreb42W3150mGmey8rg6vvlyaFBQBmpD+Rp1bniw="

services:
- docker

before-script:
# Enable experimental mode so we can use buildx.
- mkdir -p ${HOME}/.docker
- echo '{"experimental":"enabled"}' > ${HOME}/.docker/config.json
# Set up Docker authentication.
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
# This container configures QEMU for Docker buildx.
- docker run --privileged linuxkit/binfmt:v0.7
# Create a new buildx builder to do multi-arch.
- docker buildx create --driver docker-container --name multi --use
# Get the list of platforms to build on.
- "PLATFORMS=$(docker buildx inspect --bootstrap | egrep '^Platforms: ' | sed -e 's,Platforms: ,,' -e 's, ,,g')"
# Convenience so we can use "docker build" instead of "docker buildx build".
- docker buildx install

script:
- docker build -t cjyar/docker-multi-arch:${VERSION} --push --platform ${PLATFORMS} .
