addons:
  apt:
    packages:
    - docker.io

env:
  global:
  - VERSION=${TRAVIS_BRANCH}
  - DOCKER_USERNAME=cjyar
  # DOCKER_PASSWORD:
  - secure: "LHtSsr8cd6L0AtMOv6RlzENd+a8f2VdJ7vNjeHeTNkkV6Fm3Rb6UP3naVaQaMCTv0mjqgNNlM/hEcGEIisARD9WcCQojVaJxWW5YDXu9EEMCbDmiXA7BBthSq/sHCypKwUIIunvdiV47uRDkkPuQFCqMPxY+JPlZPtDymzF6MjIFIwW/t7DcfSeRUA/Q8h6Z4hVPbxaAZRvuk6nmFVn89tImi9WCiRit2kC1fS7BIlHz2DQVwEXiAzdk4szVii9UiKzR0/RjHXqEEtNmXf4SiPnHe5ZKu6DPQRF/DDYyYft/lQhFm71pYjhcwY4XcJjs2cbJsaYS2M/zzcP2bfICAZS6FfoFKHU2Mcj9SttOit/5rrj02JAzCPcofUX3umLf5rCDRmD5synrtqnNTQN0efO4S8WyheekjilMxys0djnWC5fnW2nwtNwRzdn82G56t1UfnOuKhMPhDbTnz0ubBTT3YryvDCOGYdlRks3LyKpbnVtZi2lO2Pgp8ji86LFza1MaDFEFnChzr9WOyPxyphO78sPrunOLt9NwiEKz1FqnU0SeAB1zY8q/h5jcOIGVty6MxtQmdSMPJjJeoeuThBVAsgfEVzVN+YdXLve1bVpHMzV3pH3aGLvSSGbK+v6/w5Tt2oTAOfthl5q25L/w51LN/TECDao+jvBdP39rL3o="

arch:
- amd64
- arm64
- ppc64le
- s390x

services:
- docker

before-script:
# Enable experimental mode so we can manipulate manifest lists.
- mkdir -p ${HOME}/.docker
- echo '{"experimental":"enabled"}' > ${HOME}/.docker/config.json
# Set up Docker authentication.
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

script:
# Build on this architecture, then tag and push this image.
- docker build -t test .
- docker tag test cjyar/docker-multi-arch:${TRAVIS_CPU_ARCH}-${VERSION}
- docker push cjyar/docker-multi-arch:${TRAVIS_CPU_ARCH}-${VERSION}

# This deploy stage only runs once, skipping the build matrix.
jobs:
  include:
  - stage: deploy
    script:
    # Create the manifest list which ties together all the images from the different architectures.
    - docker manifest create cjyar/docker-multi-arch:${VERSION} cjyar/docker-multi-arch:amd64-${VERSION} cjyar/docker-multi-arch:arm64-${VERSION} cjyar/docker-multi-arch:ppc64le-${VERSION} cjyar/docker-multi-arch:s390x-${VERSION}
    - docker manifest push cjyar/docker-multi-arch:${VERSION}
